### ISSUE TITLE
hardMuteVideo not work

### ISSUE THREAD

**Issue by awMinor** [ESTOS/strophe.jingle#59]
Hi, try to use hardMuteVideo method, and it tell me that no ice-ufrag, but I have this in sdp

http://i.imgur.com/eRII5ky.png

**Comment by fippo** [comment]
why do you want to use hardMute? the "soft" one which sends black video frames is usually enough.

**Comment by awMinor** [comment]
Which method should I use for it? I can see only hardMuteVideo and sendMute which send iq. I need this for turning off microphone on call.
